// <auto-generated />
using ContosoPizzaEFCoreAndRazor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContosoPizzaEFCoreAndRazor.Data.Migrations
{
    [DbContext(typeof(ContosoPizzaDBContext))]
    partial class ContosoPizzaDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ContosoPizzaEFCoreAndRazor.Models.PizzaCategories", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PizzaCategories", (string)null);
                });

            modelBuilder.Entity("ContosoPizzaEFCoreAndRazor.Models.Pizzas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PizzaCategoryID")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("PriceCategoryId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PizzaCategoryID");

                    b.ToTable("Pizzas", (string)null);
                });

            modelBuilder.Entity("ContosoPizzaEFCoreAndRazor.Models.Pizzas", b =>
                {
                    b.HasOne("ContosoPizzaEFCoreAndRazor.Models.PizzaCategories", "PizzaCategory")
                        .WithMany()
                        .HasForeignKey("PizzaCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PizzaCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
